In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split

# load data
mr = pd.read_csv('mushroom.csv', header=None)

# # # encode the values - OneHotEncoding
# label_series = pd.get_dummies(pd.Series([ val for val in mr.iloc[:,0] ]))['p']
# data_df = pd.get_dummies(mr.iloc[:,1:])

# the other way - dummy encoding (less # of cols)
label_series = pd.get_dummies(pd.Series([ val for val in mr.iloc[:,0] ]))['p']
data_df = pd.get_dummies(mr.iloc[:,1:], drop_first=True)

pd.concat([label_series, data_df], axis=1)

,p,1_c,1_f,1_k,1_s,1_x,2_g,2_s,2_y,3_c,...,21_n,21_s,21_v,21_y,22_g,22_l,22_m,22_p,22_u,22_w
0,1,0,0,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
1,0,0,0,0,0,1,0,1,0,0,...,1,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,1,0,0,0
3,1,0,0,0,0,1,0,0,1,0,...,0,1,0,0,0,0,0,0,1,0
4,0,0,0,0,0,1,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,0,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
8120,0,0,0,0,0,1,0,1,0,0,...,0,0,1,0,0,1,0,0,0,0
8121,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
8122,1,0,0,1,0,0,0,0,1,0,...,0,0,1,0,0,1,0,0,0,0
8123,0,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0

In [2]:
# split the data
data_train, data_test, label_train, label_test = train_test_split(data_df, label_series)

# train model with train ds
clf = RandomForestClassifier(n_estimators=10)
clf.fit(data_train, label_train)

# validate the model with test ds
predict = clf.predict(data_test)
ac_score = metrics.accuracy_score(label_test, predict)
cl_report = metrics.classification_report(label_test, predict)

print('ac_score :', ac_score)
print('cl_report :\n', cl_report)

ac_score : 1.0
cl_report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1058
           1       1.00      1.00      1.00       973

    accuracy                           1.00      2031
   macro avg       1.00      1.00      1.00      2031
weighted avg       1.00      1.00      1.00      2031